### ISSUE TITLE
Unable to Config Firebase files

### ISSUE THREAD

**Issue by sachinyadav9467** [PriontoAbdullah/Online-Doctors-Portal#1]
Firebase Config.js is showing errors. Please provide template for Config fields.

**Comment by PriontoAbdullah** [comment]
// firebase.config.js

const firebaseConfig = {
    apiKey: "",
    authDomain: "",
    databaseURL: "",
    projectId: "",
    storageBucket: "",
    messagingSenderId: "",
    appId: ""
};

export default firebaseConfig;
